Feature/lab 85
MiguelFerreira18/LABDSOFT_PROJECT pull request #13
Opened 2024-11-21 21:59 UTC by 1201152

## 📍 Jira ticket <img src='https://cdn.icon-icons.com/icons2/2699/PNG/512/atlassian_jira_logo_icon_170511.png' style='float: right;' alt='drawing' width='50'/> 
 Tip: Install [Jira-GitHub integration](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources) \
[Task 123](https://yourworkspace.atlassian.net/browse/123)
## 📝 Description 
Event Creaction,dashboard and detail view

## 🧪 Testing 
unit trsting in events 

## ✅ Checklist before requesting a review 

- [ ] I have made corresponding changes to the documentation.
- [ x] The code follows the defined style guide.
- [ x] I have added tests that prove my fix is effective or that my feature works.
- [ x] The code passes CI.

2024-11-22 12:18 UTC, MiguelFerreira18 requested changes
Aquelas que eu disse que não havia problema podes ou não alterar. De resto faz as alterações necessárias, corrige os merge conflicts e podes mandar

2024-11-22 12:18 UTC, MiguelFerreira18 commented on public/src/views/Events/DashboardEventsView.vue
O mesmo comentário sobre a composition APi

2024-11-22 12:18 UTC, MiguelFerreira18 commented on src/main/java/isep/ipp/pt/Smart_cities/Controller/EventController.java
> +public ResponseEntity<Event> createEvent(@RequestBody Map<String, Object> requestData) {
Se não te importares troca isto por uma class DTO, fica mais fácil de perceber o que está a ser enviado e fica menos verboso

2024-11-22 12:18 UTC, MiguelFerreira18 commented on src/main/java/isep/ipp/pt/Smart_cities/Model/EventModel/Event.java
> +    @ManyToMany(fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE })
Aqui não precisas dos attendees, a tabela subscribe trata desta parte, foi criada a tabela para se conseguir adicionar o campo status.

2024-11-22 12:18 UTC, MiguelFerreira18 commented on src/main/resources/application.properties
Isto convem voltar como estava para os testes rodarem na pipeline

2024-11-22 12:18 UTC, MiguelFerreira18 commented on src/main/java/isep/ipp/pt/Smart_cities/Model/EventModel/EventSummary.java
> +
Visto que não estás a guardar isto na base de dados não precisas das annotations Entity, Id e GeneratedValue

2024-11-22 12:18 UTC, MiguelFerreira18 commented on src/main/java/isep/ipp/pt/Smart_cities/Model/EventModel/Event.java
>      private User creator;
Posso estar enganado mas aqui só deixas Users adicionarem eventos, as Institutições à partida não conseguem adicionar nada conforme está aqui

2024-11-22 12:19 UTC, MiguelFerreira18 commented
Para os Eventos talvez vá ser necessário criar um novo campo para as Instituições e permitir que tanto este novo campo como o dos Users seja nulo

2024-11-23 09:58 UTC, 1230168-ISEP commented
Tens conflitos. Faz git merge main nesta branch para atualizar o código.

2024-11-23 14:19 UTC, MiguelFerreira18 approved these changes

2024-11-23 15:06 UTC, merged