Feature/Lab 38
MiguelFerreira18/LABDSOFT_PROJECT pull request #17
Opened 2024-11-23 11:54 UTC by SuzukeBount

## 📍 Jira ticket <img src='https://cdn.icon-icons.com/icons2/2699/PNG/512/atlassian_jira_logo_icon_170511.png' style='float: right;' alt='drawing' width='50'/> 
 Tip: Install [Jira-GitHub integration](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources) \
[Task 123](https://yourworkspace.atlassian.net/browse/123)
## 📝 Description 
 User Profile page plus theming the project

## 🧪 Testing 
All previous tests pass and the end-to-end tests in postman

## ✅ Checklist before requesting a review 

- [ ] I have made corresponding changes to the documentation.
- [ ] The code follows the defined style guide.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] The code passes CI.

## 🔗 Linked issues 
 - [LAB-89](https://isep-1230199.atlassian.net/browse/LAB-89?AtlOrigin=eyJpIjoiOTFmNzBlMDVjODgwNDFkNjg3YjE3ZDUwZTJmNzJmMjgiLCJwIjoiaiJ9)
 - [LAB-38](https://isep-1230199.atlassian.net/browse/LAB-38?atlOrigin=eyJpIjoiOTI2ODY4MjhjM2U5NDU1Yjg0NzZmYjk4MWFiYjM2ZjIiLCJwIjoiaiJ9)

2024-11-23 14:12 UTC, 1230168-ISEP commented on public/vite.config.ts.timestamp-1732225533106-6043e567f1cc4.mjs
O que são estes ficheiros ?

2024-11-23 14:12 UTC, 1230168-ISEP commented on src/main/java/isep/ipp/pt/Smart_cities/Controller/UserInfoController.java
> +        return ResponseEntity.ok(userInfoView);
Podias enviar antes o Id do user invés do email. É apenas uma nota, funciona bem assim na mesma.

2024-11-23 14:22 UTC, 1230168-ISEP approved these changes
Vou dar approve mas vê só aquela questão do ficheiro. Se for lixo temp apaga e depois podes fechar o PR

2024-11-23 14:45 UTC, MiguelFerreira18 commented on src/main/java/isep/ipp/pt/Smart_cities/Model/UserInfoModel/UserInfo.java
isto deveria de estar na class User

2024-11-23 14:48 UTC, MiguelFerreira18 requested changes
O teu UserInfo é o User, não vale a pena criar uma nova, muda o que tens para a classe User e depois podes dar merge

2024-11-24 15:28 UTC, MiguelFerreira18 approved these changes

2024-11-24 15:37 UTC, merged